version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"